version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results
            cp test-results.xml test-results/
          when: always
      - store_test_results:
          path: test-results
workflows:
  basic_test:
    jobs:
      - build_and_test
      
       
          
