version: 2.1
# orbs
orbs: 
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.4.0
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results
            cp test-results.xml test-results/
          when: always
      - store_test_results:
          path: test-results
  dependency_vulnerability_scan:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - node/install-packages
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
  build_image_push:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/check
      - docker/build: 
          image: $DOCKER_LOGIN/imagepush
      - snyk/scan:
          docker-image-name: $DOCKER_LOGIN/imagepush
          target-file: "Dockerfile"
      - docker/push:
          image: $DOCKER_LOGIN/imagepush
workflows:
  basic_test_deploy:
    jobs:
      - build_and_test
      - dependency_vulnerability_scan:
          context:
            - cci-workshop
      - build_image_push:
          requires: 
            - build_and_test
            - dependency_vulnerability_scan
          context:
            - cci-workshop
       
          
