version: 2.1
orbs: 
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results
            cp test-results.xml test-results/
          when: always
      - store_test_results:
          path: test-results
  build_image_push:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 
            name: Build and push to Docker Hub
            command: | 
              docker build -t $DOCKER_LOGIN/imagepush .
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
              docker push $DOCKER_LOGIN/imagepush
workflows:
  basic_test_deploy:
    jobs:
      - build_and_test
      - build_image_push:
          requires: 
            - build_and_test
          context:
            - cci-workshop
       
          
