version: 2.1
jobs:
  build_docker_image:
    docker: 
      - image: cimg/base:stable
    steps:
      - run: echo $PRACTICE_VARIABLE
workflows:
  basic_workflow:
    jobs:
      - build_docker_image:
          context:
            - practice_context
          
