version: 2.1
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test-ci
workflows:
  basic_test:
    jobs:
      - build_and_test
      
       
          
